name: vk_bridge
description: A dart package for working with VK Mini Apps via VK Bridge. Works web, mobile-web
homepage: https://github.com/optimist-dev/vk_bridge
version: 1.2.6

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  js: ^0.6.2
  built_value: ^7.1.0
  built_collection: ^4.3.2
  rxdart: ^0.25.0
  meta: ^1.2.4

dev_dependencies:
  test: '>=1.15.0 <2.0.0'
  build_runner: ^1.10.2
  built_value_generator: ^7.1.0